### ISSUE TITLE
UnitOfWork Order of Scheduled Operations

### ISSUE THREAD

**Issue by ocxyz** [opulencephp/orm#1]
I happened to look at the class [Opulence/Orm/UnitOfWork.php](https://github.com/opulencephp/Opulence/blob/1.0/src/Opulence/Orm/UnitOfWork.php#L74) at line 74:
```PHP
...
    try {
        $this->insert();
        $this->update();
        $this->delete();
        $this->connection->commit();
    } catch (Exception $ex) {
        ...
    }
...
````
I noticed the schedules are grouped by type of operation (INSERT, UPDATE, DELETE) and executed respectively instead of by order when each `scheduleForXXX($entity)` is actually called, I mean, if what I to achieve is an DELETE, INSERT, DELETE, UPDATE sequence.

```PHP
$unitOfWork->scheduleForDeletion($oldUser);
$unitOfWork->scheduleForInsertion($newUserWithTheSameUsername);

```
Since all INSERT operations are executed first, it will result to a database error if I have my users table constrained to have a unique username.

I hope you get what I mean :)

**Comment by davidbyoung** [comment]
Good catch.  I'll get this patched.  Thanks!

**Comment by davidbyoung** [comment]
Fixed in the latest commit to master
